### PR TITLE
ace_satDown and ace_stoodUp eventhandlers for sitting

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- Public listenable events that could help fixing the Enhanced Movement et al floating bug.

### CODE REVIEW

**Comment by commy2** [comment]
E.g.:
```sqf
["ace_satDown", {
    {
        _x attachTo [_this select 0];
    } forEach allMissionObjects "babe_helper";
}] call CBA_fnc_addEventHandler;

["ace_stoodUp", {
    {
        detach _x;
    } forEach allMissionObjects "babe_helper";

}] call CBA_fnc_addEventHandler;
```

**Comment by commy2** [comment]
E.g.:
```sqf
["ace_satDown", {
    {
        _x attachTo [_this select 0];
    } forEach allMissionObjects "babe_helper";
}] call CBA_fnc_addEventHandler;

["ace_stoodUp", {
    {
        detach _x;
    } forEach allMissionObjects "babe_helper";
}] call CBA_fnc_addEventHandler;
```

**Comment by Knight1981** [comment]
Sitting module is broken again since your rework in 3.4.0 (the floating problem) so I have to use previous version.

**Comment by jonpas** [comment]
@Knight1981 open a new issue with properly filled out template, do not resurrect old issues and pull requests and do not multi-post, thank you.

**Pull request merged**
