### PR TITLE
Add Intel Items (Documents, Photos, Notepad)

### PR DESCRIPTION
**Pull request by PabstMirror**
Edit: This PR was rewritten by mharis001 in 2019

Adds objects (carried by players as unique magazines) that hold intel.
Documents (printed text), Photos and a Notepad (editable text).

First two are designed for mission makers/zeus to add objectives in missions (marking cache locations, photos of a vip target).
The notepad can be used for anything, like recording fire missions, or leaving a message (notepads are unique)

Vanilla Arma has something similar for zeus (but not 3den as far as I can tell). But I don't really like how it works. This version uses actual objects that can be dropped/looted and doesn't just magically add briefings to an entire side.

Demo: https://www.youtube.com/watch?v=LWuGSXUVBbc
I'm honestly not sure if this fit's ACEX's scope. Aesthetically it's fairly basic, but functional.

### CODE REVIEW

**Comment by jonpas** [comment]
What about putting the clickable icons to top bar in map view?

**Comment by esteldunedain** [comment]
@PabstMirror, I really like this! the aesthetics could be improved, but it's a great adition nonetheless

> What about putting the clickable icons to top bar in map view?

Nah, I wouldn't recommend it. Maybe they could be shown using the self-interact menu instead. idk

**Comment by jonpas** [comment]
Self-intract menu on map sounds like a great place to put them IMO.

**Comment by 654wak654** [comment]
Would any of the new intel objects/ functions added with 1.76 be useful to this PR?

**Comment by mharis001** [comment]
Rewrote the component to have the aesthetic changes required. Less hard-coded and more of a framework now (as well as general improvements to the code).

No longer switches between a dialog and controls group. Simply a controls group that can be moved on the map display. 
- Fixes the flickering of the map cursor that would happen.
- Removes the black background when in focus but I don't think that is necessary.

**Comment by PabstMirror** [comment]
Thanks for reviving this, all the changes look great
I pushed a small optimization that should allow us to skip running handleLoadout in most cases.
e.g. if you just reload your weapon
it does delay requesting mag id until you actually open the map
if you have high latency, it should still work fine, but actions just won't show up for a tiny bit `func(addaction)` fails safely with a nil value
let me know what you think, but I think it's worth it because it mostly eliminates the run-time cost of this addon

**Comment by mharis001** [comment]
Good optimization 👍, and yeah don't think any delay should ever be a problem.

**Pull request merged**
